/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.layout;

import java.awt.Button;
import main.Login;
import main.Variable;
import main.action.ActionDiagnosa;
import main.action.ActionObat;
import main.action.ActionPasien;
import main.action.ActionPemeriksaan;
import main.action.ActionPendaftaran;
import main.action.ActionTindakan;

/**
 *
 * @author Muntari
 */
public class Layout extends javax.swing.JFrame {

    /**
     * Creates new form Layout
     */
    private Login log ;
    public Layout() {
        initComponents();
    }
    
    public void setLog(Login log){
        this.log = log; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmpendaftaran = new javax.swing.JMenu();
        menuPendaftaran = new javax.swing.JMenuItem();
        menuPemeriksaan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuObat = new javax.swing.JMenuItem();
        menuDiagnosa = new javax.swing.JMenuItem();
        menuTindakan = new javax.swing.JMenuItem();
        menuPasien = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Manajemen Rumah Sakit");
        setResizable(false);

        javax.swing.GroupLayout jmainLayout = new javax.swing.GroupLayout(jmain);
        jmain.setLayout(jmainLayout);
        jmainLayout.setHorizontalGroup(
            jmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jmainLayout.setVerticalGroup(
            jmainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jmpendaftaran.setText("Transaksi");
        jmpendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmpendaftaranActionPerformed(evt);
            }
        });

        menuPendaftaran.setText("Pendaftaran");
        menuPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPendaftaranActionPerformed(evt);
            }
        });
        jmpendaftaran.add(menuPendaftaran);

        menuPemeriksaan.setText("Pemeriksaan");
        menuPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPemeriksaanActionPerformed(evt);
            }
        });
        jmpendaftaran.add(menuPemeriksaan);

        jMenuBar1.add(jmpendaftaran);

        jMenu3.setText("Data Master");

        menuObat.setText("Obat");
        menuObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuObatActionPerformed(evt);
            }
        });
        jMenu3.add(menuObat);

        menuDiagnosa.setText("Diagnosa");
        menuDiagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDiagnosaActionPerformed(evt);
            }
        });
        jMenu3.add(menuDiagnosa);

        menuTindakan.setText("Tindakan");
        menuTindakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTindakanActionPerformed(evt);
            }
        });
        jMenu3.add(menuTindakan);

        menuPasien.setText("Pasien");
        menuPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPasienActionPerformed(evt);
            }
        });
        jMenu3.add(menuPasien);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Setting");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuObatActionPerformed
        jmain.removeAll();
        ActionObat obat = new ActionObat();
        jmain.setBounds(0, 0, Variable.getWidth(),Variable.getHeight());
        System.out.print(jmain.getWidth());
        obat.setBounds(10, 10, Variable.getWidth()-25, Variable.getHeight()-80);
        jmain.add(obat);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menuObatActionPerformed

    private void menuDiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDiagnosaActionPerformed
       jmain.removeAll();
        ActionDiagnosa diag = new ActionDiagnosa();
        jmain.setBounds(0, 0, Variable.getWidth(),Variable.getHeight());
        System.out.print(jmain.getWidth());
        diag.setBounds(10, 10, Variable.getWidth()-25, Variable.getHeight()-80);
        jmain.add(diag);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menuDiagnosaActionPerformed

    private void menuTindakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTindakanActionPerformed
         jmain.removeAll();
        ActionTindakan tind = new ActionTindakan();
        jmain.setBounds(0, 0, Variable.getWidth(),Variable.getHeight());
        System.out.print(jmain.getWidth());
        tind.setBounds(10, 10, Variable.getWidth()-25, Variable.getHeight()-80);
        jmain.add(tind);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menuTindakanActionPerformed

    private void menuPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPasienActionPerformed
        jmain.removeAll();
        ActionPasien pasien = new ActionPasien();
        jmain.setBounds(0, 0, Variable.getWidth(),Variable.getHeight());
        System.out.print(jmain.getWidth());
        pasien.setBounds(10, 10, Variable.getWidth()-25, Variable.getHeight()-80);
        jmain.add(pasien);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menuPasienActionPerformed

    private void jmpendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmpendaftaranActionPerformed
      
    }//GEN-LAST:event_jmpendaftaranActionPerformed

    private void menuPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPendaftaranActionPerformed
          jmain.removeAll();
        ActionPendaftaran pendaftaran = new ActionPendaftaran();
        jmain.setBounds(0, 0, Variable.getWidth(),Variable.getHeight());
        System.out.print(jmain.getWidth());
        pendaftaran.setBounds(10, 10, Variable.getWidth()-25, Variable.getHeight()-80);
        jmain.add(pendaftaran);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menuPendaftaranActionPerformed

    private void menuPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPemeriksaanActionPerformed
        jmain.removeAll();
        ActionPemeriksaan periksa = new ActionPemeriksaan();
        jmain.setBounds(0, 0, Variable.getWidth(),Variable.getHeight());
        System.out.print(jmain.getWidth());
        periksa.setBounds(10, 10, Variable.getWidth()-25, Variable.getHeight()-80);
        jmain.add(periksa);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_menuPemeriksaanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormLogin form = new FormLogin();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jmain;
    private javax.swing.JMenu jmpendaftaran;
    private javax.swing.JMenuItem menuDiagnosa;
    private javax.swing.JMenuItem menuObat;
    private javax.swing.JMenuItem menuPasien;
    private javax.swing.JMenuItem menuPemeriksaan;
    private javax.swing.JMenuItem menuPendaftaran;
    private javax.swing.JMenuItem menuTindakan;
    // End of variables declaration//GEN-END:variables
}
